### ISSUE TITLE
Question: db-mgr.hpp DbManager()

### ISSUE THREAD

**Issue by oDinZu** [brakmic/HDA-Demo#9]
In db-mgr.hpp, I have little clue what is going on here. I am learning a lot from being able to read the code, but like I stated before, this really goes deep and baffles me. Maybe you may expand on what is going on? 

I know DbManager(); is a function and then you add another DbManager& address reference, then make that equal delete, but why do two && and = delete and then the reset is super new to me.
```  
DbManager();
  DbManager(const DbManager&) = delete;
  DbManager(DbManager&&) = delete;
  DbManager& operator=(const DbManager&) = delete;
  DbManager&& operator=(DbManager&&) = delete;
  virtual ~DbManager();
```

**Comment by brakmic** [comment]
DbManager() is a special kind of a function called a [constructor](https://en.cppreference.com/w/cpp/language/constructor). I'd recommend to read "A Tour of C++" from Bjarne Stroustrup, the creator of C++. This should make a good foundation for your future C++ adventures.

**Comment by csharpee** [comment]
Alright and thanks for the *pointer*.
